param(
  [string]$OutputPath = $(if ($PSScriptRoot) { Join-Path $PSScriptRoot 'static-assets.js' } else { Join-Path (Get-Location) 'compat\static-assets.js' })
)

$scriptRoot = if ($PSScriptRoot) { $PSScriptRoot } else { Join-Path (Get-Location) 'compat' }
$projectRoot = Split-Path -Parent $scriptRoot
$assetPaths = @()

foreach ($folder in @('STAR_CHS', 'STAR_CHT')) {
  $assetPaths += Get-ChildItem -File -LiteralPath (Join-Path $projectRoot $folder) |
    ForEach-Object { Join-Path $folder $_.Name }
}

$assetPaths += @(
  'compat/runtime/emulators/wdosbox-x.js',
  'compat/runtime/emulators/wdosbox-x.wasm'
)

$lines = [System.Collections.Generic.List[string]]::new()
$lines.Add('(function () {')
$lines.Add('  const encoded = {')

foreach ($assetPath in $assetPaths) {
  $absolutePath = Join-Path $projectRoot $assetPath
  $bytes = [System.IO.File]::ReadAllBytes($absolutePath)
  $base64 = [Convert]::ToBase64String($bytes)
  $jsonKey = $assetPath.Replace('\', '/')
  $lines.Add(('    "{0}": "{1}",' -f $jsonKey, $base64))
}

$lines.Add('  };')
$lines.Add('  const keys = Object.keys(encoded);')
$lines.Add('  const byteCache = new Map();')
$lines.Add('  const textDecoder = new TextDecoder();')
$lines.Add('')
$lines.Add('  function keyFor(input) {')
$lines.Add('    const rawUrl = typeof input === "string" ? input : input && input.url;')
$lines.Add('    if (!rawUrl) return null;')
$lines.Add('    const pathname = decodeURIComponent(new URL(rawUrl, window.location.href).pathname);')
$lines.Add('    return keys.find((key) => pathname === `/${key}` || pathname.endsWith(`/${key}`)) || null;')
$lines.Add('  }')
$lines.Add('')
$lines.Add('  function bytesFor(key) {')
$lines.Add('    if (!byteCache.has(key)) {')
$lines.Add('      const binary = atob(encoded[key]);')
$lines.Add('      const bytes = new Uint8Array(binary.length);')
$lines.Add('      for (let index = 0; index < binary.length; index += 1) bytes[index] = binary.charCodeAt(index);')
$lines.Add('      byteCache.set(key, bytes);')
$lines.Add('    }')
$lines.Add('    return byteCache.get(key);')
$lines.Add('  }')
$lines.Add('')
$lines.Add('  function responseFor(key) {')
$lines.Add('    const bytes = bytesFor(key);')
$lines.Add('    return new Response(bytes.slice().buffer, { status: 200, headers: { "Content-Type": key.endsWith(".js") ? "text/javascript" : "application/octet-stream" } });')
$lines.Add('  }')
$lines.Add('')
$lines.Add('  const nativeFetch = window.fetch.bind(window);')
$lines.Add('  window.fetch = (input, init) => {')
$lines.Add('    const key = keyFor(input);')
$lines.Add('    return key ? Promise.resolve(responseFor(key)) : nativeFetch(input, init);')
$lines.Add('  };')
$lines.Add('')
$lines.Add('  const NativeXMLHttpRequest = window.XMLHttpRequest;')
$lines.Add('  class StaticAssetXMLHttpRequest {')
$lines.Add('    constructor() {')
$lines.Add('      this._native = null;')
$lines.Add('      this._listeners = new Map();')
$lines.Add('      this._responseType = "";')
$lines.Add('      this.readyState = 0;')
$lines.Add('      this.status = 0;')
$lines.Add('      this.response = null;')
$lines.Add('      this.responseText = "";')
$lines.Add('      this.responseURL = "";')
$lines.Add('      this.onreadystatechange = null;')
$lines.Add('    }')
$lines.Add('')
$lines.Add('    open(method, url, async = true) {')
$lines.Add('      this.method = method;')
$lines.Add('      this.url = url;')
$lines.Add('      this.async = async;')
$lines.Add('      this._key = keyFor(url);')
$lines.Add('      if (!this._key) {')
$lines.Add('        this._native = new NativeXMLHttpRequest();')
$lines.Add('        this._native.open(method, url, async);')
$lines.Add('        this._native.onreadystatechange = () => this._forward();')
$lines.Add('        for (const [type, handlers] of this._listeners) handlers.forEach((handler) => this._native.addEventListener(type, handler));')
$lines.Add('      }')
$lines.Add('      this.readyState = 1;')
$lines.Add('    }')
$lines.Add('')
$lines.Add('    _forward() {')
$lines.Add('      if (!this._native) return;')
$lines.Add('      this.readyState = this._native.readyState;')
$lines.Add('      this.status = this._native.status;')
$lines.Add('      this.response = this._native.response;')
$lines.Add('      this.responseText = this._native.responseText;')
$lines.Add('      this.responseURL = this._native.responseURL;')
$lines.Add('      if (this.onreadystatechange) this.onreadystatechange();')
$lines.Add('    }')
$lines.Add('')
$lines.Add('    set responseType(value) {')
$lines.Add('      this._responseType = value;')
$lines.Add('      if (this._native) this._native.responseType = value;')
$lines.Add('    }')
$lines.Add('')
$lines.Add('    get responseType() { return this._native ? this._native.responseType : this._responseType; }')
$lines.Add('    setRequestHeader(name, value) { if (this._native) this._native.setRequestHeader(name, value); }')
$lines.Add('    overrideMimeType() {}')
$lines.Add('')
$lines.Add('    addEventListener(type, handler) {')
$lines.Add('      if (!this._listeners.has(type)) this._listeners.set(type, []);')
$lines.Add('      this._listeners.get(type).push(handler);')
$lines.Add('      if (this._native) this._native.addEventListener(type, handler);')
$lines.Add('    }')
$lines.Add('')
$lines.Add('    _emit(type, event) {')
$lines.Add('      const handlers = this._listeners.get(type) || [];')
$lines.Add('      handlers.forEach((handler) => handler.call(this, event));')
$lines.Add('    }')
$lines.Add('')
$lines.Add('    send(body) {')
$lines.Add('      if (this._native) {')
$lines.Add('        this._native.send(body);')
$lines.Add('        return;')
$lines.Add('      }')
$lines.Add('      Promise.resolve().then(() => {')
$lines.Add('        const bytes = bytesFor(this._key);')
$lines.Add('        this.status = 200;')
$lines.Add('        this.responseURL = this.url;')
$lines.Add('        this.response = this._responseType === "arraybuffer" ? bytes.slice().buffer : textDecoder.decode(bytes);')
$lines.Add('        this.responseText = typeof this.response === "string" ? this.response : "";')
$lines.Add('        this.readyState = 4;')
$lines.Add('        this._emit("progress", { total: bytes.byteLength, loaded: bytes.byteLength });')
$lines.Add('        if (this.onreadystatechange) this.onreadystatechange();')
$lines.Add('      }).catch(() => { this.status = 404; this.readyState = 4; if (this.onreadystatechange) this.onreadystatechange(); this._emit("error", {}); });')
$lines.Add('    }')
$lines.Add('')
$lines.Add('    abort() {}')
$lines.Add('  }')
$lines.Add('')
$lines.Add('  window.XMLHttpRequest = StaticAssetXMLHttpRequest;')
$lines.Add('  window.STAR_DREAM_STATIC_ASSETS = { read: (path) => { const key = keyFor(path); if (!key) return Promise.reject(new Error(`静态资源不存在: ${path}`)); return Promise.resolve(responseFor(key)); } };')
$lines.Add('})();')

$outputDirectory = Split-Path -Parent $OutputPath
New-Item -ItemType Directory -Force -Path $outputDirectory | Out-Null
[System.IO.File]::WriteAllText($OutputPath, ($lines -join "`n"), [System.Text.UTF8Encoding]::new($false))
Write-Output "generated $OutputPath ($([math]::Round((Get-Item -LiteralPath $OutputPath).Length / 1MB, 2)) MB)"
